#
# Website Configuration!
#

title: A State Of Systems
description: A Systems Engineering Blog by Steven Haveman

theme: jekyll-theme-cayman

footer-links:
  email: stevenhaveman@gmail.com
  linkedin: https://www.linkedin.com/in/stevenhaveman/
  twitter: haveman
  
 url: www.astateofsystems.com
 
 gems:
  - jekyll-sitemap
  - jekyll-feed
 
 exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  
