#
# Website Configuration!
#

theme: jekyll-theme-cayman

name: A State of Systems
title: A State of Systems
description: A Systems Engineering Blog by Steven Haveman

footer-links:
  email: stevenhaveman@gmail.com
  linkedin: https://www.linkedin.com/in/stevenhaveman/
  twitter: haveman
  
url: www.astateofsystems.com

gems:
- jekyll-sitemap
- jekyll-feed

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
  
